CREATE DATABASE IF NOT EXISTS LANCHONETE;

USE LANCHONETE;

CREATE TABLE CLIENTE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CPF VARCHAR(11),
  EMAIL VARCHAR(50),
  PRIMEIRO_NOME VARCHAR(120),
  SOBRENOME VARCHAR(120),
  UNIQUE KEY UNIQUE_CPF (CPF)
);

CREATE TABLE ENDERECO (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  BAIRRO VARCHAR(30),
  CEP VARCHAR(8),
  CIDADE VARCHAR(50),
  COMPLEMENTO VARCHAR(40),
  ESTADO VARCHAR(30),
  LOGRADOURO VARCHAR(50),
  CLIENTE_ID BIGINT,
  CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE TELEFONE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  DDD VARCHAR(2),
  NUMERO VARCHAR(9),
  TIPO_TELEFONE TINYINT,
  CLIENTE_ID BIGINT,
  CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE PRODUTO (
  PRODUTO_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CATEGORIA ENUM('ACOMPANHAMENTO', 'BEBIDA', 'LANCHE', 'SOBREMESA'),
  DESCRICAO VARCHAR(200),
  NOME VARCHAR(50),
  PRECO DECIMAL(38, 2)
);

CREATE TABLE PEDIDO (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  DATA_PEDIDO TIMESTAMP(6),
  MERCADO_PAGO_ID BIGINT,
  SITUACAO TINYINT,
  VALOR_TOTAL_PEDIDO DECIMAL(38, 2),
  CLIENTE_ID BIGINT,
  CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE ITEM_PEDIDO (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO VARCHAR(100),
  QUANTIDADE INT,
  VALOR_TOTAL_ITEM DECIMAL(38, 2),
  VALOR_UNITARIO DECIMAL(38, 2),
  PEDIDO_ID BIGINT,
  CONSTRAINT FK_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
);