# Expoe a aplicação para fora do Cluster. Como NodePort, este serviço permite que a aplicação seja acessada através de qualquer node do cluster
# usando a porta especificada 30080
apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
spec:
  type: NodePort
  selector:
    app: app-lanchonete
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 8080
      nodePort: 30080