server:
  port: 8080
  servlet:
    context-path: /api/v1

tech-challenge:
  host: ${tech_challenge_host}

spring:
  application:
    name: tech-challenge
  datasource:
    url: jdbc:mysql://localhost:3307/lanchonete
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    show-sql: false
    database-platform: ${JPA_DIALECT}
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

webhook:
  mercado-pago:
    access-token: ${ACCESS_TOKEN}