server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: tech-challenge
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update