apiVersion: v1
kind: Secret
metadata:
  name: lanchonete-secret
  namespace: ns-lanchonete
type: Opaque
data:
  ACCESS_TOKEN_MP: QUFBX1VTRVItODU0NTcxMzc1ODUyODYwLTEwMDE1MDY1MjA5OWM0YWYwOTBhMTY4MDkzYjliMjNlZmU5ZTI4OTkwZg==  # Valor codificado em base64