apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-lanchonete-deployment
  namespace: ns-lanchonete
  labels:
    app: bd-lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-lanchonete
  template:
    metadata:
      labels:
        app: bd-lanchonete
    spec:
      containers:
        - name: bd-lanchonete
          image: mysql:8.4.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lanchonete-secret
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              value: lanchonete
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: lanchonete-secret
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lanchonete-secret
                  key: mysql_password