# configura um espaço de armazenamento fixo que pode ser montado em seus pods, garantindo que os dados do MySQL
# não sejam perdidos quando o pod for reiniciado ou recriado. (Não sei bem se seria útil ainda, mas não custa tentar)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lanchonete
  namespace: ns-lanchonete
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
