apiVersion: v1
kind: Service
metadata:
  name: app-lanchonete-service
  namespace: ns-lanchonete
spec:
  type: NodePort
  selector:
    app: app-lanchonete  # Seleciona os pods do Deployment da aplicação
  ports:
    - protocol: TCP
      port: 8080           # Porta do serviço
      targetPort: 8080     # Porta que o container está escutando
      nodePort: 30081      # Porta exposta no node