apiVersion: v1
kind: Service
metadata:
  name: bd-lanchonete-service
  namespace: ns-lanchonete
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: bd-lanchonete