server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: tech-challenge
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update