version: '3'
services:
  bd-lanchonete:
    image: bd-lanchonete
    container_name: bd-lanchonete
    ports:
      - "4567:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lanchonete
      MYSQL_USER: user_fiap
      MYSQL_PASSWORD: password_fiap
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["mysqld"]

volumes:
  mysql-data: